config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'
  devise_for :users
  resources :articles
  resources :home

  get '/about', to: 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    return unless user.present?
    can :read, Article
    return unless user.author?
    can :access, :rails_admin
    can :read, :dashboard
    can :manage, Article, user_id: user.id
    return unless user.admin?
    can :manage, [Article, User]


    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :cover
  validates :title, presence: true, length: {minimum: 5}
  validates :content, presence: true, length: {minimum: 500}
  validates :cover, presence: true

  def self.search(search)
    if search
      where(["content LIKE :key OR title LIKE :key", key: "%#{search}%"])
    else
      all
    end
  end

  rails_admin do
    edit do
      field :cover
      field :title
      field :content
      field :user_id, :hidden do
        default_value do
          bindings[:view]._current_user.id
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_admin_mail
  has_many :articles, dependent: :destroy

  def send_admin_mail
    pattern = /@ilpez.tech/
    unless email =~ pattern
      UserMailer.send_welcome_email(self).deliver_later
    end
  end

  rails_admin do
    edit do
      field :admin
      field :author
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :not_found }
      format.html { redirect_to main_app.root_url, alert: exception.message, status: :not_found }
      format.js   { render nothing: true, status: :not_found }
    end
  end

  def after_sign_in_path_for(resource)
    if can? :read, :dashboard
      stored_location_for(resource) || rails_admin_path
    else
      stored_location_for(resource) || root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search]).order(created_at: :desc).with_attached_cover.page(params[:page]).per(5)
    @headlines = Article.order(created_at: :desc).limit(3).with_attached_cover
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :cover, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @articles = Article.order(created_at: :desc).limit(3).offset(3).with_attached_cover
    @headlines = Article.order(created_at: :desc).limit(3).with_attached_cover
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div class="alert alert-danger mt-0">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="custom-file">
    <%= form.label :cover, class: 'custom-file-label' %>
    <%= form.file_field :cover, class: 'custom-file-input' %>
  </div>
  <div id="target"></div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>
<script type="text/javascript">
    $(function () {
        $('#article_cover').on('change', function (event) {
            var files = event.target.files;
            var image = files[0]
            var reader = new FileReader();
            reader.onload = function (file) {
                var img = new Image();
                console.log(file);
                img.src = file.target.result;
                img.width = 255
                img.height = 178
                $('#target').html(img);
            }
            reader.readAsDataURL(image);
            console.log(files);
        });
    });
</script>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Berita</h1>
<% @articles.each do |article| %>
  <div class="row mb-3">
    <div class="col-sm-4">
      <%= image_tag article.cover, class: 'img-fluid w-100' %>
    </div>
    <div class="d-flex align-items-end flex-column col-lg-8">
      <div class="">
        <h5 class="mb-1">
          <%= link_to article.title, article %>
        </h5>
        <h6 class="font-weight-light mb-1">
          <%= article.created_at.strftime("Diterbitkan %d/%b/%Y") %>
        </h6>
        <p class="text-justify d-none d-md-block mb-1">
          <%= article.content.truncate(150) %>
        </p>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @articles %>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%# if @article.cover.attached? %>
<h1><%= @article.title %></h1>
<%= image_tag @article.cover.variant(resize: "1112x518"), class: 'img-fluid rounded mx-auto d-block' %>
<%# end %>

<div class="text-justify">
  <%= simple_format @article.content %>
</div>

app/views/home/about.html.erb
<p class="text-justify">
  PT PLN (Persero) Unit Pembangunan Sulawesi Bagian Selatan merupakan salah satu unit bisnis PT PLN (Persero) yang
  memiliki tugas untuk melakukan perencanaan, pengorganisasian, pengelolaan, dan pengawasan kegiatan Pembangunan
  Pembangkit dan Jaringan Ketenagalistrikan
  di wilayah Sulawesi Bagian Selatan (Provinsi Sulawesi Selatan, Sulawesi Tenggara, dan Sulawesi Barat). <br/>Unit
  Pelaksana Proyek Pembangkit dan Jaringan Sulawesi Selatan (UPP Kitring Sulsel) sebagai salah satu unit organisasi satu
  tingkat di bawah
  Unit Induk PT. PLN (Persero) UIP Sulbagsel merupakan unit pelaksana yang dibentuk untuk memonitor kegiatan pekerjaan
  konstruksi dalam rangka peningkatan kinerja pelaksanaan pembangunan pembangkit dan jaringan.<br/>
</p>

app/views/home/index.html.erb
<h1>Berita Terbaru</h1>
<div class="row">
  <% @articles.each.with_index do |article, index| %>
    <% if index.zero? %>
      <div class="col-sm-8">
        <div class="row-cols-1 m-0 w-100">
          <%= image_tag article.cover, class: 'rounded w-100' %>
          <p>
            <%= link_to article.title, article %>
          </p>
          <p class="text-justify d-none d-md-block">
            <%= article.content.truncate(300) %>
          </p>
        </div>
      </div>
      <div class="col-sm-4">
    <% else %>
      <div class="row-cols-1 m-0">
        <%= image_tag article.cover, class: 'rounded w-100' %>
        <p>
          <%= link_to article.title, article %>
        </p>
        <p class="text-justify d-none d-md-block">
          <%= article.content.truncate(150) %>
        </p>
      </div>
    <% end %>
  <% end %>
  </div>
</div>
<div class="row">
  <%= link_to "BACA LEBIH LANJUT", articles_url, class: 'btn btn-link btn-block more-button', role: 'button' %>
</div>

app/views/layouts/_headlines.html.erb
<% if action_name == 'index' %>
  <div id="headline" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#headline" data-slide-to="0"></li>
      <li data-target="#headline" data-slide-to="1"></li>
      <li data-target="#headline" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <% @headlines.each.with_index do |article, index| %>
        <div class="carousel-item <%= index.zero? ? 'active' : '' %>" data-interval="5000">
          <%= image_tag article.cover, class: 'img-fluid d-block w-100' %>
          <div class="jumbotron carousel-caption">
            <div class="d-none d-sm-block">
              <h1><%= article.title %></h1>
            </div>
            <div class="d-none d-md-block">
              <p><%= article.content.truncate(150) %></p>
            </div>
            <%= button_to 'Selengkapnya', article, method: :get, class: 'btn btn-primary' %>
            <!--          <p></p>-->
          </div>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#headline" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#headline" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% elsif current_page? about_path %>
  <div id=tentang>
    <div class="jumbotron">
      <h1 class="text-center">Tentang Kami</h1>
    </div>
  </div>
<% end %>

app/views/layouts/_new_session.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-group">
    <%= f.label :email %><br/>
    <%= f.email_field :email, class: 'form-control', autofocus: true, autocomplete: "email" %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br/>
    <div class="input-group" id="show_hide_password">
      <%= f.password_field :password, class: 'form-control', autocomplete: "current-password" %>
      <div class="input-group-append">
        <a href="" class="input-group-text text-decoration-none">
          <i class="fa fa-eye-slash" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="form-group form-check">
      <%= f.check_box :remember_me, {class: 'form-check-input'} %>
      <%= f.label :remember_me, {class: 'form-check-label'} %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in", {class: 'btn btn-primary'} %>
  </div>
<% end %>

<%= render "users/shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="id">
<head>
  <title>Portal Berita PLN UPP Kitring</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag asset_path('pln.ico') %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
<header>
  <nav class="navbar navbar-dark bg-primary navbar-expand-md">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= url_for root_path %>"></a>
      <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
        <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav mx-auto justify-content-center">
          <li class="nav-item">
            <a class="nav-link" href="<%= url_for about_path %>">TENTANG</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://portal.pln.co.id/">PLN</a></li>
          <li class="nav-item"></li>
        </ul>
        <ul class="nav navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-search"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right p-3">
              <%= form_with(model: Article, method: 'get', local: true) do %>
                <div class="form-group">
                  <%#= label_tag :search, "Cari" %>
                  <%= text_field_tag :search, nil, class: 'form-control' %>
                </div>
                <%= submit_tag "Cari", class: 'btn btn-primary btn-block' %>
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right p-3">
              <% if user_signed_in? %>
                <%= current_user.email %>
                <% if can? :read, :dashboard %>
                  <%= link_to 'Dashboard', rails_admin_path, class: 'dropdown-item' %>
                <% end %>

                <%= link_to('Edit Account', edit_user_registration_path, class: 'dropdown-item') %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'dropdown-item') %>

              <% else %>
                <%= render 'layouts/new_session' %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<% if action_name == 'index' or action_name == 'about' %>
  <%= render "layouts/headlines" %>
<% end %>
<% unless flash.empty? %>
  <!--  <div style="position: absolute; top: 10%; right: 1rem;">-->
  <div class="d-flex justify-content-center">
    <% flash.each do |type, message| %>
      <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="3000">
        <div class="toast-body <%= type == 'alert' ? 'alert-danger' : 'alert-primary' %>">
          <div class="font-weight-bolder"><%= message %></div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<script type="text/javascript">
    $('.toast').toast('show')
</script>
<main class="container">
  <%= yield %>
</main>
<footer>
  <div class="footer-dark">
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-12 item">
            <h3 class="text-center">CONTACT</h3>
            <ul>
              <li>
                <a class="loc" href="https://goo.gl/maps/ihGNyikv5RHgqVhZ7"><i class="fa fa-location-arrow"></i></a>
              </li>
              <li><a class="telp" href="tel:123"><i class="fa fa-phone"></i></a></li>
              <li>
                <a class="mail" href="mailto:pln123@pln.co.id?subject=PLN%20UIP%20Sulbagsel"><i class="fa fa-envelope"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <p class="copyright"></p>
      </div>
    </footer>
  </div>
</footer>
<script type="text/javascript">
    $(document).ready(function () {
        let listener_tag = $("#show_hide_password a");
        let input_tag = $("#show_hide_password input");
        let icon_tag;
        icon_tag = $("#show_hide_password i");
        listener_tag.on('click', function (event) {
                event.preventDefault();
                if (input_tag.attr("type") === "password") {
                    input_tag.attr("type", "text");
                    icon_tag.removeClass("fa-eye-slash");
                    icon_tag.addClass("fa-eye");
                } else if (input_tag.attr("type") === "text") {
                    input_tag.attr("type", "password");
                    icon_tag.removeClass("fa-eye");
                    icon_tag.addClass("fa-eye-slash");
                }
            }
        );
    });
</script>
</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>